spring.application.name=gateway-server
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.service-id=config-server
spring.config.import=optional:configserver:
server.port=8080
spring.cloud.gateway.routes[0].id=stats-server
spring.cloud.gateway.routes[0].uri=lb://stats-server
spring.cloud.gateway.routes[0].predicates[0]=Path=/hit,/stats
spring.cloud.gateway.routes[1].id=main-service
spring.cloud.gateway.routes[1].uri=lb://main-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/**
