spring.application.name=aggregator
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.config.import=optional:configserver:http://localhost:8888
server.port=0
spring.kafka.bootstrap-servers=localhost:9092
