spring.application.name=event-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.config.import=optional:configserver:http://localhost:8888
server.port=0
spring.datasource.url=jdbc:postgresql://localhost:5432/ewm
spring.datasource.username=ewm
spring.datasource.password=ewm
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
grpc.client.collector.address=discovery:///collector
grpc.client.collector.enableKeepAlive=true
grpc.client.collector.keepAliveWithoutCalls=true
grpc.client.collector.negotiationType=plaintext
grpc.client.analyzer.address=discovery:///analyzer
grpc.client.analyzer.enableKeepAlive=true
grpc.client.analyzer.keepAliveWithoutCalls=true
grpc.client.analyzer.negotiationType=plaintext
