grpc.server.port=9091
spring.kafka.bootstrap-servers=localhost:9092
spring.datasource.url=jdbc:postgresql://analyzer-db:5432/ewm_analyzer
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
