server.port=8080
spring.cloud.gateway.routes[0].id=stats-server
spring.cloud.gateway.routes[0].uri=lb://stats-server
spring.cloud.gateway.routes[0].predicates[0]=Path=/hit,/stats
spring.cloud.gateway.routes[1].id=ewm-service
spring.cloud.gateway.routes[1].uri=lb://ewm-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/**
