spring.application.name=stats-server
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
spring.config.import=optional:configserver:http://config-server:8888
server.port=9090
spring.datasource.url=jdbc:postgresql://stats-db:5432/stats
spring.datasource.username=stats
spring.datasource.password=stats
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop
